// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_robocup_ssl_geometry.proto

#ifndef PROTOBUF_messages_5frobocup_5fssl_5fgeometry_2eproto__INCLUDED
#define PROTOBUF_messages_5frobocup_5fssl_5fgeometry_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();

class Vector2f;
class SSL_FieldLineSegment;
class SSL_FieldCicularArc;
class SSL_GeometryFieldSize;
class SSL_GeometryCameraCalibration;
class SSL_GeometryData;

// ===================================================================

class Vector2f : public ::google::protobuf::Message {
 public:
  Vector2f();
  virtual ~Vector2f();

  Vector2f(const Vector2f& from);

  inline Vector2f& operator=(const Vector2f& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector2f& default_instance();

  void Swap(Vector2f* other);

  // implements Message ----------------------------------------------

  Vector2f* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Vector2f& from);
  void MergeFrom(const Vector2f& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);

  // required float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);

  // @@protoc_insertion_point(class_scope:Vector2f)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  float x_;
  float y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();

  void InitAsDefaultInstance();
  static Vector2f* default_instance_;
};
// -------------------------------------------------------------------

class SSL_FieldLineSegment : public ::google::protobuf::Message {
 public:
  SSL_FieldLineSegment();
  virtual ~SSL_FieldLineSegment();

  SSL_FieldLineSegment(const SSL_FieldLineSegment& from);

  inline SSL_FieldLineSegment& operator=(const SSL_FieldLineSegment& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_FieldLineSegment& default_instance();

  void Swap(SSL_FieldLineSegment* other);

  // implements Message ----------------------------------------------

  SSL_FieldLineSegment* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SSL_FieldLineSegment& from);
  void MergeFrom(const SSL_FieldLineSegment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .Vector2f p1 = 2;
  inline bool has_p1() const;
  inline void clear_p1();
  static const int kP1FieldNumber = 2;
  inline const ::Vector2f& p1() const;
  inline ::Vector2f* mutable_p1();
  inline ::Vector2f* release_p1();
  inline void set_allocated_p1(::Vector2f* p1);

  // required .Vector2f p2 = 3;
  inline bool has_p2() const;
  inline void clear_p2();
  static const int kP2FieldNumber = 3;
  inline const ::Vector2f& p2() const;
  inline ::Vector2f* mutable_p2();
  inline ::Vector2f* release_p2();
  inline void set_allocated_p2(::Vector2f* p2);

  // required float thickness = 4;
  inline bool has_thickness() const;
  inline void clear_thickness();
  static const int kThicknessFieldNumber = 4;
  inline float thickness() const;
  inline void set_thickness(float value);

  // @@protoc_insertion_point(class_scope:SSL_FieldLineSegment)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_p1();
  inline void clear_has_p1();
  inline void set_has_p2();
  inline void clear_has_p2();
  inline void set_has_thickness();
  inline void clear_has_thickness();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::Vector2f* p1_;
  ::Vector2f* p2_;
  float thickness_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();

  void InitAsDefaultInstance();
  static SSL_FieldLineSegment* default_instance_;
};
// -------------------------------------------------------------------

class SSL_FieldCicularArc : public ::google::protobuf::Message {
 public:
  SSL_FieldCicularArc();
  virtual ~SSL_FieldCicularArc();

  SSL_FieldCicularArc(const SSL_FieldCicularArc& from);

  inline SSL_FieldCicularArc& operator=(const SSL_FieldCicularArc& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_FieldCicularArc& default_instance();

  void Swap(SSL_FieldCicularArc* other);

  // implements Message ----------------------------------------------

  SSL_FieldCicularArc* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SSL_FieldCicularArc& from);
  void MergeFrom(const SSL_FieldCicularArc& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .Vector2f center = 2;
  inline bool has_center() const;
  inline void clear_center();
  static const int kCenterFieldNumber = 2;
  inline const ::Vector2f& center() const;
  inline ::Vector2f* mutable_center();
  inline ::Vector2f* release_center();
  inline void set_allocated_center(::Vector2f* center);

  // required float radius = 3;
  inline bool has_radius() const;
  inline void clear_radius();
  static const int kRadiusFieldNumber = 3;
  inline float radius() const;
  inline void set_radius(float value);

  // required float a1 = 4;
  inline bool has_a1() const;
  inline void clear_a1();
  static const int kA1FieldNumber = 4;
  inline float a1() const;
  inline void set_a1(float value);

  // required float a2 = 5;
  inline bool has_a2() const;
  inline void clear_a2();
  static const int kA2FieldNumber = 5;
  inline float a2() const;
  inline void set_a2(float value);

  // required float thickness = 6;
  inline bool has_thickness() const;
  inline void clear_thickness();
  static const int kThicknessFieldNumber = 6;
  inline float thickness() const;
  inline void set_thickness(float value);

  // @@protoc_insertion_point(class_scope:SSL_FieldCicularArc)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_center();
  inline void clear_has_center();
  inline void set_has_radius();
  inline void clear_has_radius();
  inline void set_has_a1();
  inline void clear_has_a1();
  inline void set_has_a2();
  inline void clear_has_a2();
  inline void set_has_thickness();
  inline void clear_has_thickness();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::Vector2f* center_;
  float radius_;
  float a1_;
  float a2_;
  float thickness_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();

  void InitAsDefaultInstance();
  static SSL_FieldCicularArc* default_instance_;
};
// -------------------------------------------------------------------

class SSL_GeometryFieldSize : public ::google::protobuf::Message {
 public:
  SSL_GeometryFieldSize();
  virtual ~SSL_GeometryFieldSize();

  SSL_GeometryFieldSize(const SSL_GeometryFieldSize& from);

  inline SSL_GeometryFieldSize& operator=(const SSL_GeometryFieldSize& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_GeometryFieldSize& default_instance();

  void Swap(SSL_GeometryFieldSize* other);

  // implements Message ----------------------------------------------

  SSL_GeometryFieldSize* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SSL_GeometryFieldSize& from);
  void MergeFrom(const SSL_GeometryFieldSize& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 field_length = 1;
  inline bool has_field_length() const;
  inline void clear_field_length();
  static const int kFieldLengthFieldNumber = 1;
  inline ::google::protobuf::int32 field_length() const;
  inline void set_field_length(::google::protobuf::int32 value);

  // required int32 field_width = 2;
  inline bool has_field_width() const;
  inline void clear_field_width();
  static const int kFieldWidthFieldNumber = 2;
  inline ::google::protobuf::int32 field_width() const;
  inline void set_field_width(::google::protobuf::int32 value);

  // required int32 goal_width = 3;
  inline bool has_goal_width() const;
  inline void clear_goal_width();
  static const int kGoalWidthFieldNumber = 3;
  inline ::google::protobuf::int32 goal_width() const;
  inline void set_goal_width(::google::protobuf::int32 value);

  // required int32 goal_depth = 4;
  inline bool has_goal_depth() const;
  inline void clear_goal_depth();
  static const int kGoalDepthFieldNumber = 4;
  inline ::google::protobuf::int32 goal_depth() const;
  inline void set_goal_depth(::google::protobuf::int32 value);

  // required int32 boundary_width = 5;
  inline bool has_boundary_width() const;
  inline void clear_boundary_width();
  static const int kBoundaryWidthFieldNumber = 5;
  inline ::google::protobuf::int32 boundary_width() const;
  inline void set_boundary_width(::google::protobuf::int32 value);

  // repeated .SSL_FieldLineSegment field_lines = 6;
  inline int field_lines_size() const;
  inline void clear_field_lines();
  static const int kFieldLinesFieldNumber = 6;
  inline const ::SSL_FieldLineSegment& field_lines(int index) const;
  inline ::SSL_FieldLineSegment* mutable_field_lines(int index);
  inline ::SSL_FieldLineSegment* add_field_lines();
  inline const ::google::protobuf::RepeatedPtrField< ::SSL_FieldLineSegment >&
      field_lines() const;
  inline ::google::protobuf::RepeatedPtrField< ::SSL_FieldLineSegment >*
      mutable_field_lines();

  // repeated .SSL_FieldCicularArc field_arcs = 7;
  inline int field_arcs_size() const;
  inline void clear_field_arcs();
  static const int kFieldArcsFieldNumber = 7;
  inline const ::SSL_FieldCicularArc& field_arcs(int index) const;
  inline ::SSL_FieldCicularArc* mutable_field_arcs(int index);
  inline ::SSL_FieldCicularArc* add_field_arcs();
  inline const ::google::protobuf::RepeatedPtrField< ::SSL_FieldCicularArc >&
      field_arcs() const;
  inline ::google::protobuf::RepeatedPtrField< ::SSL_FieldCicularArc >*
      mutable_field_arcs();

  // @@protoc_insertion_point(class_scope:SSL_GeometryFieldSize)
 private:
  inline void set_has_field_length();
  inline void clear_has_field_length();
  inline void set_has_field_width();
  inline void clear_has_field_width();
  inline void set_has_goal_width();
  inline void clear_has_goal_width();
  inline void set_has_goal_depth();
  inline void clear_has_goal_depth();
  inline void set_has_boundary_width();
  inline void clear_has_boundary_width();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 field_length_;
  ::google::protobuf::int32 field_width_;
  ::google::protobuf::int32 goal_width_;
  ::google::protobuf::int32 goal_depth_;
  ::google::protobuf::RepeatedPtrField< ::SSL_FieldLineSegment > field_lines_;
  ::google::protobuf::RepeatedPtrField< ::SSL_FieldCicularArc > field_arcs_;
  ::google::protobuf::int32 boundary_width_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();

  void InitAsDefaultInstance();
  static SSL_GeometryFieldSize* default_instance_;
};
// -------------------------------------------------------------------

class SSL_GeometryCameraCalibration : public ::google::protobuf::Message {
 public:
  SSL_GeometryCameraCalibration();
  virtual ~SSL_GeometryCameraCalibration();

  SSL_GeometryCameraCalibration(const SSL_GeometryCameraCalibration& from);

  inline SSL_GeometryCameraCalibration& operator=(const SSL_GeometryCameraCalibration& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_GeometryCameraCalibration& default_instance();

  void Swap(SSL_GeometryCameraCalibration* other);

  // implements Message ----------------------------------------------

  SSL_GeometryCameraCalibration* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SSL_GeometryCameraCalibration& from);
  void MergeFrom(const SSL_GeometryCameraCalibration& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 camera_id = 1;
  inline bool has_camera_id() const;
  inline void clear_camera_id();
  static const int kCameraIdFieldNumber = 1;
  inline ::google::protobuf::uint32 camera_id() const;
  inline void set_camera_id(::google::protobuf::uint32 value);

  // required float focal_length = 2;
  inline bool has_focal_length() const;
  inline void clear_focal_length();
  static const int kFocalLengthFieldNumber = 2;
  inline float focal_length() const;
  inline void set_focal_length(float value);

  // required float principal_point_x = 3;
  inline bool has_principal_point_x() const;
  inline void clear_principal_point_x();
  static const int kPrincipalPointXFieldNumber = 3;
  inline float principal_point_x() const;
  inline void set_principal_point_x(float value);

  // required float principal_point_y = 4;
  inline bool has_principal_point_y() const;
  inline void clear_principal_point_y();
  static const int kPrincipalPointYFieldNumber = 4;
  inline float principal_point_y() const;
  inline void set_principal_point_y(float value);

  // required float distortion = 5;
  inline bool has_distortion() const;
  inline void clear_distortion();
  static const int kDistortionFieldNumber = 5;
  inline float distortion() const;
  inline void set_distortion(float value);

  // required float q0 = 6;
  inline bool has_q0() const;
  inline void clear_q0();
  static const int kQ0FieldNumber = 6;
  inline float q0() const;
  inline void set_q0(float value);

  // required float q1 = 7;
  inline bool has_q1() const;
  inline void clear_q1();
  static const int kQ1FieldNumber = 7;
  inline float q1() const;
  inline void set_q1(float value);

  // required float q2 = 8;
  inline bool has_q2() const;
  inline void clear_q2();
  static const int kQ2FieldNumber = 8;
  inline float q2() const;
  inline void set_q2(float value);

  // required float q3 = 9;
  inline bool has_q3() const;
  inline void clear_q3();
  static const int kQ3FieldNumber = 9;
  inline float q3() const;
  inline void set_q3(float value);

  // required float tx = 10;
  inline bool has_tx() const;
  inline void clear_tx();
  static const int kTxFieldNumber = 10;
  inline float tx() const;
  inline void set_tx(float value);

  // required float ty = 11;
  inline bool has_ty() const;
  inline void clear_ty();
  static const int kTyFieldNumber = 11;
  inline float ty() const;
  inline void set_ty(float value);

  // required float tz = 12;
  inline bool has_tz() const;
  inline void clear_tz();
  static const int kTzFieldNumber = 12;
  inline float tz() const;
  inline void set_tz(float value);

  // optional float derived_camera_world_tx = 13;
  inline bool has_derived_camera_world_tx() const;
  inline void clear_derived_camera_world_tx();
  static const int kDerivedCameraWorldTxFieldNumber = 13;
  inline float derived_camera_world_tx() const;
  inline void set_derived_camera_world_tx(float value);

  // optional float derived_camera_world_ty = 14;
  inline bool has_derived_camera_world_ty() const;
  inline void clear_derived_camera_world_ty();
  static const int kDerivedCameraWorldTyFieldNumber = 14;
  inline float derived_camera_world_ty() const;
  inline void set_derived_camera_world_ty(float value);

  // optional float derived_camera_world_tz = 15;
  inline bool has_derived_camera_world_tz() const;
  inline void clear_derived_camera_world_tz();
  static const int kDerivedCameraWorldTzFieldNumber = 15;
  inline float derived_camera_world_tz() const;
  inline void set_derived_camera_world_tz(float value);

  // @@protoc_insertion_point(class_scope:SSL_GeometryCameraCalibration)
 private:
  inline void set_has_camera_id();
  inline void clear_has_camera_id();
  inline void set_has_focal_length();
  inline void clear_has_focal_length();
  inline void set_has_principal_point_x();
  inline void clear_has_principal_point_x();
  inline void set_has_principal_point_y();
  inline void clear_has_principal_point_y();
  inline void set_has_distortion();
  inline void clear_has_distortion();
  inline void set_has_q0();
  inline void clear_has_q0();
  inline void set_has_q1();
  inline void clear_has_q1();
  inline void set_has_q2();
  inline void clear_has_q2();
  inline void set_has_q3();
  inline void clear_has_q3();
  inline void set_has_tx();
  inline void clear_has_tx();
  inline void set_has_ty();
  inline void clear_has_ty();
  inline void set_has_tz();
  inline void clear_has_tz();
  inline void set_has_derived_camera_world_tx();
  inline void clear_has_derived_camera_world_tx();
  inline void set_has_derived_camera_world_ty();
  inline void clear_has_derived_camera_world_ty();
  inline void set_has_derived_camera_world_tz();
  inline void clear_has_derived_camera_world_tz();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 camera_id_;
  float focal_length_;
  float principal_point_x_;
  float principal_point_y_;
  float distortion_;
  float q0_;
  float q1_;
  float q2_;
  float q3_;
  float tx_;
  float ty_;
  float tz_;
  float derived_camera_world_tx_;
  float derived_camera_world_ty_;
  float derived_camera_world_tz_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(15 + 31) / 32];

  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();

  void InitAsDefaultInstance();
  static SSL_GeometryCameraCalibration* default_instance_;
};
// -------------------------------------------------------------------

class SSL_GeometryData : public ::google::protobuf::Message {
 public:
  SSL_GeometryData();
  virtual ~SSL_GeometryData();

  SSL_GeometryData(const SSL_GeometryData& from);

  inline SSL_GeometryData& operator=(const SSL_GeometryData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_GeometryData& default_instance();

  void Swap(SSL_GeometryData* other);

  // implements Message ----------------------------------------------

  SSL_GeometryData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SSL_GeometryData& from);
  void MergeFrom(const SSL_GeometryData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .SSL_GeometryFieldSize field = 1;
  inline bool has_field() const;
  inline void clear_field();
  static const int kFieldFieldNumber = 1;
  inline const ::SSL_GeometryFieldSize& field() const;
  inline ::SSL_GeometryFieldSize* mutable_field();
  inline ::SSL_GeometryFieldSize* release_field();
  inline void set_allocated_field(::SSL_GeometryFieldSize* field);

  // repeated .SSL_GeometryCameraCalibration calib = 2;
  inline int calib_size() const;
  inline void clear_calib();
  static const int kCalibFieldNumber = 2;
  inline const ::SSL_GeometryCameraCalibration& calib(int index) const;
  inline ::SSL_GeometryCameraCalibration* mutable_calib(int index);
  inline ::SSL_GeometryCameraCalibration* add_calib();
  inline const ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >&
      calib() const;
  inline ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >*
      mutable_calib();

  // @@protoc_insertion_point(class_scope:SSL_GeometryData)
 private:
  inline void set_has_field();
  inline void clear_has_field();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::SSL_GeometryFieldSize* field_;
  ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration > calib_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_AssignDesc_messages_5frobocup_5fssl_5fgeometry_2eproto();
  friend void protobuf_ShutdownFile_messages_5frobocup_5fssl_5fgeometry_2eproto();

  void InitAsDefaultInstance();
  static SSL_GeometryData* default_instance_;
};
// ===================================================================


// ===================================================================

// Vector2f

// required float x = 1;
inline bool Vector2f::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector2f::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector2f::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector2f::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Vector2f::x() const {
  return x_;
}
inline void Vector2f::set_x(float value) {
  set_has_x();
  x_ = value;
}

// required float y = 2;
inline bool Vector2f::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector2f::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector2f::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector2f::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Vector2f::y() const {
  return y_;
}
inline void Vector2f::set_y(float value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// SSL_FieldLineSegment

// required string name = 1;
inline bool SSL_FieldLineSegment::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_FieldLineSegment::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_FieldLineSegment::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SSL_FieldLineSegment::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& SSL_FieldLineSegment::name() const {
  return *name_;
}
inline void SSL_FieldLineSegment::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void SSL_FieldLineSegment::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void SSL_FieldLineSegment::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SSL_FieldLineSegment::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* SSL_FieldLineSegment::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SSL_FieldLineSegment::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required .Vector2f p1 = 2;
inline bool SSL_FieldLineSegment::has_p1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SSL_FieldLineSegment::set_has_p1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SSL_FieldLineSegment::clear_has_p1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SSL_FieldLineSegment::clear_p1() {
  if (p1_ != NULL) p1_->::Vector2f::Clear();
  clear_has_p1();
}
inline const ::Vector2f& SSL_FieldLineSegment::p1() const {
  return p1_ != NULL ? *p1_ : *default_instance_->p1_;
}
inline ::Vector2f* SSL_FieldLineSegment::mutable_p1() {
  set_has_p1();
  if (p1_ == NULL) p1_ = new ::Vector2f;
  return p1_;
}
inline ::Vector2f* SSL_FieldLineSegment::release_p1() {
  clear_has_p1();
  ::Vector2f* temp = p1_;
  p1_ = NULL;
  return temp;
}
inline void SSL_FieldLineSegment::set_allocated_p1(::Vector2f* p1) {
  delete p1_;
  p1_ = p1;
  if (p1) {
    set_has_p1();
  } else {
    clear_has_p1();
  }
}

// required .Vector2f p2 = 3;
inline bool SSL_FieldLineSegment::has_p2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SSL_FieldLineSegment::set_has_p2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SSL_FieldLineSegment::clear_has_p2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SSL_FieldLineSegment::clear_p2() {
  if (p2_ != NULL) p2_->::Vector2f::Clear();
  clear_has_p2();
}
inline const ::Vector2f& SSL_FieldLineSegment::p2() const {
  return p2_ != NULL ? *p2_ : *default_instance_->p2_;
}
inline ::Vector2f* SSL_FieldLineSegment::mutable_p2() {
  set_has_p2();
  if (p2_ == NULL) p2_ = new ::Vector2f;
  return p2_;
}
inline ::Vector2f* SSL_FieldLineSegment::release_p2() {
  clear_has_p2();
  ::Vector2f* temp = p2_;
  p2_ = NULL;
  return temp;
}
inline void SSL_FieldLineSegment::set_allocated_p2(::Vector2f* p2) {
  delete p2_;
  p2_ = p2;
  if (p2) {
    set_has_p2();
  } else {
    clear_has_p2();
  }
}

// required float thickness = 4;
inline bool SSL_FieldLineSegment::has_thickness() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SSL_FieldLineSegment::set_has_thickness() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SSL_FieldLineSegment::clear_has_thickness() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SSL_FieldLineSegment::clear_thickness() {
  thickness_ = 0;
  clear_has_thickness();
}
inline float SSL_FieldLineSegment::thickness() const {
  return thickness_;
}
inline void SSL_FieldLineSegment::set_thickness(float value) {
  set_has_thickness();
  thickness_ = value;
}

// -------------------------------------------------------------------

// SSL_FieldCicularArc

// required string name = 1;
inline bool SSL_FieldCicularArc::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_FieldCicularArc::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_FieldCicularArc::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SSL_FieldCicularArc::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& SSL_FieldCicularArc::name() const {
  return *name_;
}
inline void SSL_FieldCicularArc::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void SSL_FieldCicularArc::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void SSL_FieldCicularArc::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SSL_FieldCicularArc::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* SSL_FieldCicularArc::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SSL_FieldCicularArc::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required .Vector2f center = 2;
inline bool SSL_FieldCicularArc::has_center() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SSL_FieldCicularArc::set_has_center() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SSL_FieldCicularArc::clear_has_center() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SSL_FieldCicularArc::clear_center() {
  if (center_ != NULL) center_->::Vector2f::Clear();
  clear_has_center();
}
inline const ::Vector2f& SSL_FieldCicularArc::center() const {
  return center_ != NULL ? *center_ : *default_instance_->center_;
}
inline ::Vector2f* SSL_FieldCicularArc::mutable_center() {
  set_has_center();
  if (center_ == NULL) center_ = new ::Vector2f;
  return center_;
}
inline ::Vector2f* SSL_FieldCicularArc::release_center() {
  clear_has_center();
  ::Vector2f* temp = center_;
  center_ = NULL;
  return temp;
}
inline void SSL_FieldCicularArc::set_allocated_center(::Vector2f* center) {
  delete center_;
  center_ = center;
  if (center) {
    set_has_center();
  } else {
    clear_has_center();
  }
}

// required float radius = 3;
inline bool SSL_FieldCicularArc::has_radius() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SSL_FieldCicularArc::set_has_radius() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SSL_FieldCicularArc::clear_has_radius() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SSL_FieldCicularArc::clear_radius() {
  radius_ = 0;
  clear_has_radius();
}
inline float SSL_FieldCicularArc::radius() const {
  return radius_;
}
inline void SSL_FieldCicularArc::set_radius(float value) {
  set_has_radius();
  radius_ = value;
}

// required float a1 = 4;
inline bool SSL_FieldCicularArc::has_a1() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SSL_FieldCicularArc::set_has_a1() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SSL_FieldCicularArc::clear_has_a1() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SSL_FieldCicularArc::clear_a1() {
  a1_ = 0;
  clear_has_a1();
}
inline float SSL_FieldCicularArc::a1() const {
  return a1_;
}
inline void SSL_FieldCicularArc::set_a1(float value) {
  set_has_a1();
  a1_ = value;
}

// required float a2 = 5;
inline bool SSL_FieldCicularArc::has_a2() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SSL_FieldCicularArc::set_has_a2() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SSL_FieldCicularArc::clear_has_a2() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SSL_FieldCicularArc::clear_a2() {
  a2_ = 0;
  clear_has_a2();
}
inline float SSL_FieldCicularArc::a2() const {
  return a2_;
}
inline void SSL_FieldCicularArc::set_a2(float value) {
  set_has_a2();
  a2_ = value;
}

// required float thickness = 6;
inline bool SSL_FieldCicularArc::has_thickness() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SSL_FieldCicularArc::set_has_thickness() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SSL_FieldCicularArc::clear_has_thickness() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SSL_FieldCicularArc::clear_thickness() {
  thickness_ = 0;
  clear_has_thickness();
}
inline float SSL_FieldCicularArc::thickness() const {
  return thickness_;
}
inline void SSL_FieldCicularArc::set_thickness(float value) {
  set_has_thickness();
  thickness_ = value;
}

// -------------------------------------------------------------------

// SSL_GeometryFieldSize

// required int32 field_length = 1;
inline bool SSL_GeometryFieldSize::has_field_length() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_field_length() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_GeometryFieldSize::clear_has_field_length() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SSL_GeometryFieldSize::clear_field_length() {
  field_length_ = 0;
  clear_has_field_length();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::field_length() const {
  return field_length_;
}
inline void SSL_GeometryFieldSize::set_field_length(::google::protobuf::int32 value) {
  set_has_field_length();
  field_length_ = value;
}

// required int32 field_width = 2;
inline bool SSL_GeometryFieldSize::has_field_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_field_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SSL_GeometryFieldSize::clear_has_field_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SSL_GeometryFieldSize::clear_field_width() {
  field_width_ = 0;
  clear_has_field_width();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::field_width() const {
  return field_width_;
}
inline void SSL_GeometryFieldSize::set_field_width(::google::protobuf::int32 value) {
  set_has_field_width();
  field_width_ = value;
}

// required int32 goal_width = 3;
inline bool SSL_GeometryFieldSize::has_goal_width() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_goal_width() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SSL_GeometryFieldSize::clear_has_goal_width() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SSL_GeometryFieldSize::clear_goal_width() {
  goal_width_ = 0;
  clear_has_goal_width();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::goal_width() const {
  return goal_width_;
}
inline void SSL_GeometryFieldSize::set_goal_width(::google::protobuf::int32 value) {
  set_has_goal_width();
  goal_width_ = value;
}

// required int32 goal_depth = 4;
inline bool SSL_GeometryFieldSize::has_goal_depth() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_goal_depth() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SSL_GeometryFieldSize::clear_has_goal_depth() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SSL_GeometryFieldSize::clear_goal_depth() {
  goal_depth_ = 0;
  clear_has_goal_depth();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::goal_depth() const {
  return goal_depth_;
}
inline void SSL_GeometryFieldSize::set_goal_depth(::google::protobuf::int32 value) {
  set_has_goal_depth();
  goal_depth_ = value;
}

// required int32 boundary_width = 5;
inline bool SSL_GeometryFieldSize::has_boundary_width() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SSL_GeometryFieldSize::set_has_boundary_width() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SSL_GeometryFieldSize::clear_has_boundary_width() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SSL_GeometryFieldSize::clear_boundary_width() {
  boundary_width_ = 0;
  clear_has_boundary_width();
}
inline ::google::protobuf::int32 SSL_GeometryFieldSize::boundary_width() const {
  return boundary_width_;
}
inline void SSL_GeometryFieldSize::set_boundary_width(::google::protobuf::int32 value) {
  set_has_boundary_width();
  boundary_width_ = value;
}

// repeated .SSL_FieldLineSegment field_lines = 6;
inline int SSL_GeometryFieldSize::field_lines_size() const {
  return field_lines_.size();
}
inline void SSL_GeometryFieldSize::clear_field_lines() {
  field_lines_.Clear();
}
inline const ::SSL_FieldLineSegment& SSL_GeometryFieldSize::field_lines(int index) const {
  return field_lines_.Get(index);
}
inline ::SSL_FieldLineSegment* SSL_GeometryFieldSize::mutable_field_lines(int index) {
  return field_lines_.Mutable(index);
}
inline ::SSL_FieldLineSegment* SSL_GeometryFieldSize::add_field_lines() {
  return field_lines_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SSL_FieldLineSegment >&
SSL_GeometryFieldSize::field_lines() const {
  return field_lines_;
}
inline ::google::protobuf::RepeatedPtrField< ::SSL_FieldLineSegment >*
SSL_GeometryFieldSize::mutable_field_lines() {
  return &field_lines_;
}

// repeated .SSL_FieldCicularArc field_arcs = 7;
inline int SSL_GeometryFieldSize::field_arcs_size() const {
  return field_arcs_.size();
}
inline void SSL_GeometryFieldSize::clear_field_arcs() {
  field_arcs_.Clear();
}
inline const ::SSL_FieldCicularArc& SSL_GeometryFieldSize::field_arcs(int index) const {
  return field_arcs_.Get(index);
}
inline ::SSL_FieldCicularArc* SSL_GeometryFieldSize::mutable_field_arcs(int index) {
  return field_arcs_.Mutable(index);
}
inline ::SSL_FieldCicularArc* SSL_GeometryFieldSize::add_field_arcs() {
  return field_arcs_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SSL_FieldCicularArc >&
SSL_GeometryFieldSize::field_arcs() const {
  return field_arcs_;
}
inline ::google::protobuf::RepeatedPtrField< ::SSL_FieldCicularArc >*
SSL_GeometryFieldSize::mutable_field_arcs() {
  return &field_arcs_;
}

// -------------------------------------------------------------------

// SSL_GeometryCameraCalibration

// required uint32 camera_id = 1;
inline bool SSL_GeometryCameraCalibration::has_camera_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_camera_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_GeometryCameraCalibration::clear_has_camera_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SSL_GeometryCameraCalibration::clear_camera_id() {
  camera_id_ = 0u;
  clear_has_camera_id();
}
inline ::google::protobuf::uint32 SSL_GeometryCameraCalibration::camera_id() const {
  return camera_id_;
}
inline void SSL_GeometryCameraCalibration::set_camera_id(::google::protobuf::uint32 value) {
  set_has_camera_id();
  camera_id_ = value;
}

// required float focal_length = 2;
inline bool SSL_GeometryCameraCalibration::has_focal_length() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_focal_length() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SSL_GeometryCameraCalibration::clear_has_focal_length() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SSL_GeometryCameraCalibration::clear_focal_length() {
  focal_length_ = 0;
  clear_has_focal_length();
}
inline float SSL_GeometryCameraCalibration::focal_length() const {
  return focal_length_;
}
inline void SSL_GeometryCameraCalibration::set_focal_length(float value) {
  set_has_focal_length();
  focal_length_ = value;
}

// required float principal_point_x = 3;
inline bool SSL_GeometryCameraCalibration::has_principal_point_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_principal_point_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SSL_GeometryCameraCalibration::clear_has_principal_point_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SSL_GeometryCameraCalibration::clear_principal_point_x() {
  principal_point_x_ = 0;
  clear_has_principal_point_x();
}
inline float SSL_GeometryCameraCalibration::principal_point_x() const {
  return principal_point_x_;
}
inline void SSL_GeometryCameraCalibration::set_principal_point_x(float value) {
  set_has_principal_point_x();
  principal_point_x_ = value;
}

// required float principal_point_y = 4;
inline bool SSL_GeometryCameraCalibration::has_principal_point_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_principal_point_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SSL_GeometryCameraCalibration::clear_has_principal_point_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SSL_GeometryCameraCalibration::clear_principal_point_y() {
  principal_point_y_ = 0;
  clear_has_principal_point_y();
}
inline float SSL_GeometryCameraCalibration::principal_point_y() const {
  return principal_point_y_;
}
inline void SSL_GeometryCameraCalibration::set_principal_point_y(float value) {
  set_has_principal_point_y();
  principal_point_y_ = value;
}

// required float distortion = 5;
inline bool SSL_GeometryCameraCalibration::has_distortion() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_distortion() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SSL_GeometryCameraCalibration::clear_has_distortion() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SSL_GeometryCameraCalibration::clear_distortion() {
  distortion_ = 0;
  clear_has_distortion();
}
inline float SSL_GeometryCameraCalibration::distortion() const {
  return distortion_;
}
inline void SSL_GeometryCameraCalibration::set_distortion(float value) {
  set_has_distortion();
  distortion_ = value;
}

// required float q0 = 6;
inline bool SSL_GeometryCameraCalibration::has_q0() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_q0() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SSL_GeometryCameraCalibration::clear_has_q0() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SSL_GeometryCameraCalibration::clear_q0() {
  q0_ = 0;
  clear_has_q0();
}
inline float SSL_GeometryCameraCalibration::q0() const {
  return q0_;
}
inline void SSL_GeometryCameraCalibration::set_q0(float value) {
  set_has_q0();
  q0_ = value;
}

// required float q1 = 7;
inline bool SSL_GeometryCameraCalibration::has_q1() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_q1() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SSL_GeometryCameraCalibration::clear_has_q1() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SSL_GeometryCameraCalibration::clear_q1() {
  q1_ = 0;
  clear_has_q1();
}
inline float SSL_GeometryCameraCalibration::q1() const {
  return q1_;
}
inline void SSL_GeometryCameraCalibration::set_q1(float value) {
  set_has_q1();
  q1_ = value;
}

// required float q2 = 8;
inline bool SSL_GeometryCameraCalibration::has_q2() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_q2() {
  _has_bits_[0] |= 0x00000080u;
}
inline void SSL_GeometryCameraCalibration::clear_has_q2() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void SSL_GeometryCameraCalibration::clear_q2() {
  q2_ = 0;
  clear_has_q2();
}
inline float SSL_GeometryCameraCalibration::q2() const {
  return q2_;
}
inline void SSL_GeometryCameraCalibration::set_q2(float value) {
  set_has_q2();
  q2_ = value;
}

// required float q3 = 9;
inline bool SSL_GeometryCameraCalibration::has_q3() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_q3() {
  _has_bits_[0] |= 0x00000100u;
}
inline void SSL_GeometryCameraCalibration::clear_has_q3() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void SSL_GeometryCameraCalibration::clear_q3() {
  q3_ = 0;
  clear_has_q3();
}
inline float SSL_GeometryCameraCalibration::q3() const {
  return q3_;
}
inline void SSL_GeometryCameraCalibration::set_q3(float value) {
  set_has_q3();
  q3_ = value;
}

// required float tx = 10;
inline bool SSL_GeometryCameraCalibration::has_tx() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_tx() {
  _has_bits_[0] |= 0x00000200u;
}
inline void SSL_GeometryCameraCalibration::clear_has_tx() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void SSL_GeometryCameraCalibration::clear_tx() {
  tx_ = 0;
  clear_has_tx();
}
inline float SSL_GeometryCameraCalibration::tx() const {
  return tx_;
}
inline void SSL_GeometryCameraCalibration::set_tx(float value) {
  set_has_tx();
  tx_ = value;
}

// required float ty = 11;
inline bool SSL_GeometryCameraCalibration::has_ty() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_ty() {
  _has_bits_[0] |= 0x00000400u;
}
inline void SSL_GeometryCameraCalibration::clear_has_ty() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void SSL_GeometryCameraCalibration::clear_ty() {
  ty_ = 0;
  clear_has_ty();
}
inline float SSL_GeometryCameraCalibration::ty() const {
  return ty_;
}
inline void SSL_GeometryCameraCalibration::set_ty(float value) {
  set_has_ty();
  ty_ = value;
}

// required float tz = 12;
inline bool SSL_GeometryCameraCalibration::has_tz() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_tz() {
  _has_bits_[0] |= 0x00000800u;
}
inline void SSL_GeometryCameraCalibration::clear_has_tz() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void SSL_GeometryCameraCalibration::clear_tz() {
  tz_ = 0;
  clear_has_tz();
}
inline float SSL_GeometryCameraCalibration::tz() const {
  return tz_;
}
inline void SSL_GeometryCameraCalibration::set_tz(float value) {
  set_has_tz();
  tz_ = value;
}

// optional float derived_camera_world_tx = 13;
inline bool SSL_GeometryCameraCalibration::has_derived_camera_world_tx() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_derived_camera_world_tx() {
  _has_bits_[0] |= 0x00001000u;
}
inline void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tx() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void SSL_GeometryCameraCalibration::clear_derived_camera_world_tx() {
  derived_camera_world_tx_ = 0;
  clear_has_derived_camera_world_tx();
}
inline float SSL_GeometryCameraCalibration::derived_camera_world_tx() const {
  return derived_camera_world_tx_;
}
inline void SSL_GeometryCameraCalibration::set_derived_camera_world_tx(float value) {
  set_has_derived_camera_world_tx();
  derived_camera_world_tx_ = value;
}

// optional float derived_camera_world_ty = 14;
inline bool SSL_GeometryCameraCalibration::has_derived_camera_world_ty() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_derived_camera_world_ty() {
  _has_bits_[0] |= 0x00002000u;
}
inline void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_ty() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void SSL_GeometryCameraCalibration::clear_derived_camera_world_ty() {
  derived_camera_world_ty_ = 0;
  clear_has_derived_camera_world_ty();
}
inline float SSL_GeometryCameraCalibration::derived_camera_world_ty() const {
  return derived_camera_world_ty_;
}
inline void SSL_GeometryCameraCalibration::set_derived_camera_world_ty(float value) {
  set_has_derived_camera_world_ty();
  derived_camera_world_ty_ = value;
}

// optional float derived_camera_world_tz = 15;
inline bool SSL_GeometryCameraCalibration::has_derived_camera_world_tz() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void SSL_GeometryCameraCalibration::set_has_derived_camera_world_tz() {
  _has_bits_[0] |= 0x00004000u;
}
inline void SSL_GeometryCameraCalibration::clear_has_derived_camera_world_tz() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void SSL_GeometryCameraCalibration::clear_derived_camera_world_tz() {
  derived_camera_world_tz_ = 0;
  clear_has_derived_camera_world_tz();
}
inline float SSL_GeometryCameraCalibration::derived_camera_world_tz() const {
  return derived_camera_world_tz_;
}
inline void SSL_GeometryCameraCalibration::set_derived_camera_world_tz(float value) {
  set_has_derived_camera_world_tz();
  derived_camera_world_tz_ = value;
}

// -------------------------------------------------------------------

// SSL_GeometryData

// required .SSL_GeometryFieldSize field = 1;
inline bool SSL_GeometryData::has_field() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_GeometryData::set_has_field() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_GeometryData::clear_has_field() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SSL_GeometryData::clear_field() {
  if (field_ != NULL) field_->::SSL_GeometryFieldSize::Clear();
  clear_has_field();
}
inline const ::SSL_GeometryFieldSize& SSL_GeometryData::field() const {
  return field_ != NULL ? *field_ : *default_instance_->field_;
}
inline ::SSL_GeometryFieldSize* SSL_GeometryData::mutable_field() {
  set_has_field();
  if (field_ == NULL) field_ = new ::SSL_GeometryFieldSize;
  return field_;
}
inline ::SSL_GeometryFieldSize* SSL_GeometryData::release_field() {
  clear_has_field();
  ::SSL_GeometryFieldSize* temp = field_;
  field_ = NULL;
  return temp;
}
inline void SSL_GeometryData::set_allocated_field(::SSL_GeometryFieldSize* field) {
  delete field_;
  field_ = field;
  if (field) {
    set_has_field();
  } else {
    clear_has_field();
  }
}

// repeated .SSL_GeometryCameraCalibration calib = 2;
inline int SSL_GeometryData::calib_size() const {
  return calib_.size();
}
inline void SSL_GeometryData::clear_calib() {
  calib_.Clear();
}
inline const ::SSL_GeometryCameraCalibration& SSL_GeometryData::calib(int index) const {
  return calib_.Get(index);
}
inline ::SSL_GeometryCameraCalibration* SSL_GeometryData::mutable_calib(int index) {
  return calib_.Mutable(index);
}
inline ::SSL_GeometryCameraCalibration* SSL_GeometryData::add_calib() {
  return calib_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >&
SSL_GeometryData::calib() const {
  return calib_;
}
inline ::google::protobuf::RepeatedPtrField< ::SSL_GeometryCameraCalibration >*
SSL_GeometryData::mutable_calib() {
  return &calib_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messages_5frobocup_5fssl_5fgeometry_2eproto__INCLUDED
